# Site settings
title: Matthew Staley
email: staley.d.matthew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "When we try to pick out anything by istelf, we find it hitched to everything else in the Universe." -- John Muir
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthewdstaley.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  matthewdstaley

# Build settings
markdown: kramdown
