# Site settings
title: Matthew D. Staley
email: staley.d.matthew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my webpage! I have posted a few articles and documents pertaining to my lifes hobbies and interests. Enjnoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthewdstaley.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  matthewdstaley

# Build settings
markdown: kramdown
